/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.ac.ncl.cascade.daa.sign;

public class topographia_daa_sign {
  public static String getSignResult() {
    return topographia_daa_signJNI.getSignResult();
  }

  public static void setSignResult(String result) {
    topographia_daa_signJNI.setSignResult(result);
  }

  public static int tp_daa_sign(String[] argc) {
    return topographia_daa_signJNI.tp_daa_sign(argc);
  }

}
