/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.ac.ncl.cascade.daa.sign;

public class topographia_daa_signJNI {
  public final static native String getSignResult();
  public final static native void setSignResult(String jarg1);
  public final static native int tp_daa_sign(String[] jarg1);
}
