/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.ac.ncl.cascade.daa.join;

public class topographia_daa_joinJNI {
  public final static native String getNG();
  public final static native void setNG(String jarg1);
  public final static native int tp_daa_join(String[] jarg1);
}
