/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.ac.ncl.cascade.daa.join;

public class topographia_daa_join {
  public static String getNG() {
    return topographia_daa_joinJNI.getNG();
  }

  public static void setNG(String newNG) {
    topographia_daa_joinJNI.setNG(newNG);
  }

  public static int tp_daa_join(String[] argc) {
    return topographia_daa_joinJNI.tp_daa_join(argc);
  }

}
